"""Generate docs/canary/README.md methodology file."""

from pathlib import Path
from typing import Any

from canary.sites import SITES


def generate_readme(history: list[dict[str, Any]], path: Path) -> None:
    last_ts = history[-1]["ts"] if history else "no runs yet"
    site_lines = "\n".join(
        f"- **{s['name']}** — `{s['url']}` ({s['key']})" for s in SITES
    )
    content = f"""# ASB Canary — Public Detection Score

This directory is **generated automatically** by the canary runner. Do not edit
`index.html`, `badge.svg`, or `history.jsonl` by hand.

Last run: `{last_ts}`

## What this measures

Every four hours, a headless AgentBrowser session visits six public detection
sites (three fingerprint analyzers, three real-world challenge pages). Each site
is scored as `pass`, `soft-detect`, `detected`, or `fail`. The overall score is:

```
score = (passes × 1.0 + soft-detects × 0.5) / 6 × 100
```

Sites tested:

{site_lines}

## What this does NOT measure

- Your application's business logic or login flows
- Rate limits, IP reputation, or proxy quality in production
- Long-session behavior or account warming effectiveness
- Every anti-bot vendor (only a fixed public sample)

## Privacy

This site is generated by an automated test browser. We do not log user data.
No cookies or credentials from real users are used. History is append-only JSONL
committed to this repository for transparency.

## Alerting

If the score stays below 75% for three consecutive runs, the GitHub Action
opens an issue. See `.github/workflows/canary.yml`.
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")